"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MainWindow.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(name="DCCui",
    version=".01-dev",
    author="Daniel Hayes",
    author_email="d@danielhayes.net",
    description="A generic UI setup for DCC applications.",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
