# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dccui.ui'
#
# Created: Sun Oct 21 19:51:01 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DCCUI(object):
    def setupUi(self, DCCUI):
        DCCUI.setObjectName("DCCUI")
        DCCUI.resize(1043, 949)
        DCCUI.setDocumentMode(False)
        DCCUI.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks)
        self.centralwidget = QtGui.QWidget(DCCUI)
        self.centralwidget.setObjectName("centralwidget")
        DCCUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DCCUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuNodegraph = QtGui.QMenu(self.menubar)
        self.menuNodegraph.setObjectName("menuNodegraph")
        self.menuAdd_Nodes = QtGui.QMenu(self.menuNodegraph)
        self.menuAdd_Nodes.setObjectName("menuAdd_Nodes")
        self.menuTesting = QtGui.QMenu(self.menuAdd_Nodes)
        self.menuTesting.setObjectName("menuTesting")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuNew_Floating_Window = QtGui.QMenu(self.menuWindow)
        self.menuNew_Floating_Window.setObjectName("menuNew_Floating_Window")
        self.menuSaved_Layouts_2 = QtGui.QMenu(self.menuWindow)
        self.menuSaved_Layouts_2.setObjectName("menuSaved_Layouts_2")
        DCCUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DCCUI)
        self.statusbar.setObjectName("statusbar")
        DCCUI.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(DCCUI)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(DCCUI)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(DCCUI)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(DCCUI)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionQuit = QtGui.QAction(DCCUI)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCut = QtGui.QAction(DCCUI)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(DCCUI)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(DCCUI)
        self.actionPaste.setObjectName("actionPaste")
        self.actionTesting = QtGui.QAction(DCCUI)
        self.actionTesting.setObjectName("actionTesting")
        self.actionDocs = QtGui.QAction(DCCUI)
        self.actionDocs.setObjectName("actionDocs")
        self.actionAbout = QtGui.QAction(DCCUI)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDuplicate = QtGui.QAction(DCCUI)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.actionIgnore_Node = QtGui.QAction(DCCUI)
        self.actionIgnore_Node.setObjectName("actionIgnore_Node")
        self.actionExtract_Node = QtGui.QAction(DCCUI)
        self.actionExtract_Node.setObjectName("actionExtract_Node")
        self.actionEdit_Node = QtGui.QAction(DCCUI)
        self.actionEdit_Node.setObjectName("actionEdit_Node")
        self.actionView_Node = QtGui.QAction(DCCUI)
        self.actionView_Node.setObjectName("actionView_Node")
        self.actionSave_Layout = QtGui.QAction(DCCUI)
        self.actionSave_Layout.setObjectName("actionSave_Layout")
        self.actionTesting_2 = QtGui.QAction(DCCUI)
        self.actionTesting_2.setObjectName("actionTesting_2")
        self.actionTesting_Add_Node = QtGui.QAction(DCCUI)
        self.actionTesting_Add_Node.setObjectName("actionTesting_Add_Node")
        self.actionSelect_All = QtGui.QAction(DCCUI)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionTest_Windows = QtGui.QAction(DCCUI)
        self.actionTest_Windows.setObjectName("actionTest_Windows")
        self.actionSave_Layout_2 = QtGui.QAction(DCCUI)
        self.actionSave_Layout_2.setObjectName("actionSave_Layout_2")
        self.actionTest_Saved_Layouts = QtGui.QAction(DCCUI)
        self.actionTest_Saved_Layouts.setObjectName("actionTest_Saved_Layouts")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuHelp.addAction(self.actionDocs)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTesting.addAction(self.actionTesting_Add_Node)
        self.menuAdd_Nodes.addAction(self.menuTesting.menuAction())
        self.menuNodegraph.addAction(self.menuAdd_Nodes.menuAction())
        self.menuNodegraph.addAction(self.actionExtract_Node)
        self.menuNodegraph.addAction(self.actionIgnore_Node)
        self.menuNodegraph.addAction(self.actionEdit_Node)
        self.menuNodegraph.addAction(self.actionView_Node)
        self.menuNew_Floating_Window.addAction(self.actionTest_Windows)
        self.menuSaved_Layouts_2.addAction(self.actionTest_Saved_Layouts)
        self.menuWindow.addAction(self.menuNew_Floating_Window.menuAction())
        self.menuWindow.addAction(self.actionSave_Layout_2)
        self.menuWindow.addAction(self.menuSaved_Layouts_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuNodegraph.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DCCUI)
        QtCore.QMetaObject.connectSlotsByName(DCCUI)

    def retranslateUi(self, DCCUI):
        DCCUI.setWindowTitle(QtGui.QApplication.translate("DCCUI", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DCCUI", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DCCUI", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("DCCUI", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNodegraph.setTitle(QtGui.QApplication.translate("DCCUI", "Nodegraph", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_Nodes.setTitle(QtGui.QApplication.translate("DCCUI", "Add Nodes...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTesting.setTitle(QtGui.QApplication.translate("DCCUI", "Testing Node Subcat", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("DCCUI", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew_Floating_Window.setTitle(QtGui.QApplication.translate("DCCUI", "New Floating Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSaved_Layouts_2.setTitle(QtGui.QApplication.translate("DCCUI", "Saved Layouts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DCCUI", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("DCCUI", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DCCUI", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("DCCUI", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DCCUI", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("DCCUI", "Exit the program.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("DCCUI", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("DCCUI", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("DCCUI", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTesting.setText(QtGui.QApplication.translate("DCCUI", "Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTesting.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+Shift+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocs.setText(QtGui.QApplication.translate("DCCUI", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("DCCUI", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setText(QtGui.QApplication.translate("DCCUI", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIgnore_Node.setText(QtGui.QApplication.translate("DCCUI", "Ignore Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIgnore_Node.setShortcut(QtGui.QApplication.translate("DCCUI", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract_Node.setText(QtGui.QApplication.translate("DCCUI", "Extract Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtract_Node.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Node.setText(QtGui.QApplication.translate("DCCUI", "Edit Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Node.setShortcut(QtGui.QApplication.translate("DCCUI", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Node.setText(QtGui.QApplication.translate("DCCUI", "View Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Node.setShortcut(QtGui.QApplication.translate("DCCUI", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Layout.setText(QtGui.QApplication.translate("DCCUI", "Save Layout...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTesting_2.setText(QtGui.QApplication.translate("DCCUI", "Saved Layout Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTesting_Add_Node.setText(QtGui.QApplication.translate("DCCUI", "Testing Add Node", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("DCCUI", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setShortcut(QtGui.QApplication.translate("DCCUI", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Windows.setText(QtGui.QApplication.translate("DCCUI", "Test Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Layout_2.setText(QtGui.QApplication.translate("DCCUI", "Save Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Saved_Layouts.setText(QtGui.QApplication.translate("DCCUI", "Test Saved Layouts", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DCCUI = QtGui.QMainWindow()
    ui = Ui_DCCUI()
    ui.setupUi(DCCUI)
    DCCUI.show()
    sys.exit(app.exec_())

