from PySide import QtGui, QtCore
from stylesheet import *
from stylesheet_rc import *

import math
Pi = math.pi
TwoPi = 2.0 * Pi

#MW GLOBALS
MW_WINSIZE = (1024, 768)
MW_FB_SIZE = (.5, .5)
MW_PM_SIZE = (.3, .5)

#NODE GLOBALS
NODE_MINIMUM_SIZE = QtCore.QRectF(-40, -40, 80, 40)
NODE_HORIZ_PAD = 3
NODE_VERT_PAD = 5
NODE_CORNER_RADIUS = (3, 3)
NODE_DEFAULT_NAME = 'Node'
NODE_DEFAULT_COLOR = QtGui.QColor(90, 90, 90, 255)
NODE_BORDER_COLOR = QtCore.Qt.black
NODE_BORDER_SIZE = 3
NODE_TEXT_COLOR = QtCore.Qt.black
NODE_SELECTED_BORDER_COLOR = QtCore.Qt.yellow
NODE_Z_VAL = 0
NODE_LABEL_WPAD = 4
NODE_IGNORED_COLOR = QtGui.QColor(170, 90, 90, 255)
NODE_IGNORED_LINESIZE = 5

#PORT GLOBALS
PORT_BORDER_COLOR = QtCore.Qt.black
PORT_COLOR = QtGui.QColor(127, 127, 127, 255)
PORT_HIGHLIGHT_COLOR = QtCore.Qt.yellow
PORT_SIZE = 7
PORT_IN_ZVAL = 5
PORT_OUT_ZVAL = 20

#SWITCH GLOBALS
SWITCH_OFF_COLOR = QtGui.QColor(25, 25, 25, 255)
SWITCH_DEFAULT_ON_COLOR = QtGui.QColor(150, 0, 0, 255)
SWITCH_BORDER_COLOR = QtCore.Qt.black
SWITCH_SIZE = 6

#EDGE GLOBALS
EDGE_ARROW_SIZE = 10.0
EDGE_LINE_WIDTH = 3.0
EDGE_COLOR = QtCore.Qt.black
EDGE_HIGHLIGHT_COLOR = QtCore.Qt.yellow
EDGE_Z_VAL = 10

#FB GLOABLS
FRAMEBUFFER_BG_COL = QtGui.QColor(50, 50, 50, 255)
FRAMEBUFFER_VIEW_PAD = 50

#DEFAULT KEYS
FOCUS = QtCore.Qt.Key_F
DRAW_CONNECT = '`'
EDIT = QtCore.Qt.Key_E
VIEW = QtCore.Qt.Key_V
